dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-macie-member
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-macie-member v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-macie-member/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: KONm2zUpJO5nXEdW/Ql1VLHtPh0C4TKUPIBz+EFdMDHVFhBRiQrV+LKU4mLaNEY3cj3xkdTyxfDqpcovwP9xlC7oB0v6EsJgVrbeK+IE1TnDa+Xn/1XQ/b6p7+KfWc2BsooJEuLQiI6BB52kV89TbayYV+UaDqUTwuhz1RNkRcvrCyYI5m9GwA+8hIHwfs7em76b0HA38aPt0OhJAEjBBd1mshnTvnZTNdbFpK7t0crIrwaiKszVkTU5JWRf4xUumcJqF5W6oszKvAMutxSSgcHSZgdZajWbmZ9xDi3w6WCjcUU6L7VJTLbGovmps9EK8ZsDRwzhjK46TKV7kvtgoi3y26VXeHF8qJF1qIg9n03RGuzz084iuI74MyY+7kv16XB4TX1pjpa45Y336u75QY13ysOlGfsAZUfjABhcV6jZacrIRixr8+013jNdZOw3K3BBiVzSXowihJ4n4dAU9ohrYf2LqLDan4XbSjmFY/NxloGS7Y1rZtP1G49KJwMlhemyYH/9W3q1+uZtEcG8Kd6Ek6hSBACajegAYcSQndNdj5tghoOcDt/DHPh0A+qdyay4+yqsqXAqJIgWlcmfCs6vZFrNxYx1pUnsBQDuZ5MIybcrkjVonCEc2YCj+LwZ0hURRgltX7nEMGUnaLd7GgJLG4pZp9Tqj4KiYTMvMW0=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-macie-member
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
